.base: &base
  hostname: 185.178.46.12
  user: mtish
  port: 22
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  identityFile: /deployment/decrypted_credentials/id_rsa_deployment


test:
  <<: *base
  branch: deployer
  stage: develop
  deploy_path: /var/www/circletest
